[project]
name = "ai-cv-critiquer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jasun-Maharjan", email = "jsnmhrjn@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.2",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.2.3",
    "streamlit>=1.63.0",
]

[project.scripts]
ai-cv-critiquer = "ai_cv_critiquer:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
